version: "3"
services:
  backend:
    container_name: backend 
    build:
        context: ./docker/express
    depends_on:
      - db  
    volumes:
      - ./express:/usr/app
      - /usr/app/node_modules
    environment:  
      - MONGO_URL=mongodb://db:27017/todos
      - APP_PORT=80
    ports: ['80:80'] 

  db:
    container_name: db
    image: mongo:4.0
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./docker/vue
    volumes:
      - ./vue:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    environment:  
      - BACKEND_URL=http://localhost/todos